name: free ci

on:
  push:
    branches: [ free ]
    paths-ignore:
      - 'Pictures/**'
      - '*.md'
      - '*.html'
      - '*.json'
  pull_request:
    branches: [ free ]
    paths-ignore:
      - 'Pictures/**'
      - '*.md'
      - '*.html'
      - '*.json'
  workflow_dispatch:

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: lucifiel/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install
        run: |
          npm install
      - name: Check
        run: |
          npm run check:tsc
      - name: Run linter
        run: |
          npm run lint
          npm run csslint
